[package]
name = "pam-sober-2"
version = "0.1.0"
authors = ["Anthony Nowell <anowell@gmail.com>"]

[lib]
name = "pam_sober_2"
crate-type = ["cdylib"]

[dependencies]
pam-bindings = { path = "../pam/" }
rand = "0.8.4"
