[package]

name = "pam-bindings"
description = "PAM bindings for Rust"
version = "0.1.2"
authors = [ "Anthony Nowell <anowell@gmail.com>" ]
repository = "https://github.com/anowell/pam-rs"
readme = "../README.md"
keywords = ["pam", "ffi", "linux", "authentication"]
license = "MIT"

[lib]
name = "pam"

[dependencies]
libc = "0.2.97"
